spring:
 application:
  name: "configserver"
 profiles:
  #active: native
  active: git
 cloud:
  config: 
   server:
    #native:
     #search-locations: "classpath:/config"
     #search-locations: "file:///C://Users//rogen//OneDrive//Documentos//config"
    git:
     uri: "https://github.com/Samuelrcf/eazybytes-microservices-config.git"
     default-label: main
     timeout: 5
     clone-on-start: true
     force-pull: true

management: 
 endpoints:
  web:
   exposure:
    include: "*"  
 health:
  readiness-state:
   enabled: true
  liveness-state:
   enabled: true
 endpoint: #mencionar endpoints específicos
  health:
   probes:
    enabled: true  
     
encrypt:
 key: "45D81EC1EF61DF9AD8D3E5BB397F9"
server:
 port: 8083
